image: Visual Studio 2015
build: off
test: off

#---------------------------------#
#    environment configuration    #
#---------------------------------#

shallow_clone: true
platform: x64
environment:
  NODEJS_VERSION: "8"

# Things to install after repo clone
install:
  - SET "PATH=%PATH%;C:\Program Files\Git\mingw64\libexec\git-core" # For weird git bug
  - ps: Install-Product node $env:NODEJS_VERSION $env:Platform
  - node --version
  - npm --version
  - npm config set msvs_version 2015
  - npm run bootstrap
  - npm test

cache:
  - '%USERPROFILE%\.electron -> packages/insomnia-app/package.json'

#---------------------------------#
#       tests configuration       #
#---------------------------------#

build_script:
  - npm install --no-save 7zip-bin-win app-builder-bin-win
  - npm run app-package

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: packages\insomnia-app\dist\squirrel-windows\*
    name: dist

# #---------------------------------#
# #     deployment configuration    #
# #---------------------------------#

# deploy:
#   description: ''
#   provider: GitHub
#   auth_token:
#     secure: 99623c6683cb84099c2db8a6aa25e1b7981ea676
#   artifact: dist
#   prerelease: true
